export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export const WALLPAPERS = [
  { id: "default", label: "Default Mesh", class: "bg-base-100" },
  { id: "dots", label: "Neural Dots", class: "bg-base-100 bg-[radial-gradient(currentColor_1px,transparent_1px)] [background-size:20px_24px] text-base-content/10" },
  { id: "grid", label: "Cyber Grid", class: "bg-base-100 bg-[linear-gradient(currentColor_1px,transparent_1px),linear-gradient(90deg,currentColor_1px,transparent_1px)] [background-size:40px_40px] text-base-content/10" },
  { id: "sunset", label: "Solar Flare", class: "bg-gradient-to-br from-orange-500/5 via-rose-500/5 to-amber-500/5" },
  { id: "ocean", label: "Deep Sea", class: "bg-gradient-to-br from-blue-500/5 via-cyan-500/5 to-emerald-500/5" },
  { id: "space", label: "Dark Matter", class: "bg-neutral bg-[radial-gradient(#ffffff10_1px,transparent_1px)] [background-size:30px_30px]" },
  { id: "carbon", label: "Carbon Fiber", class: "bg-neutral-focus bg-[linear-gradient(45deg,rgba(0,0,0,0.1)_25%,transparent_25%,transparent_75%,rgba(0,0,0,0.1)_75%,rgba(0,0,0,0.1)),linear-gradient(45deg,rgba(0,0,0,0.1)_25%,transparent_25%,transparent_75%,rgba(0,0,0,0.1)_75%,rgba(0,0,0,0.1))] [background-position:0_0,15px_15px] [background-size:30px_30px]" },
];
